packages:
  - "apps/*"
  - "packages/*"

"strict-dep-builds": false
"verify-deps-before-run": false

onlyBuiltDependencies:
  - esbuild
neverBuiltDependencies:
  - electron
allowBuilds:
  better-sqlite3: true
  electron: false
  esbuild: true
